job_hub_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: JobHubBundle:Default:index }

job_hub_accueil:
    pattern:  /index
    defaults: { _controller: JobHubBundle:JobHub:index }

job_hub_session:
    pattern:  /session
    defaults: { _controller: JobHubBundle:JobHub:session }
    
job_hub_candidat:
    pattern:  /candidat
    defaults: { _controller: JobHubBundle:JobHub:candidat }

job_hub_entreprise:
    pattern:  /entreprise
    defaults: { _controller: JobHubBundle:JobHub:entreprise }
    
job_hub_cv:
    pattern:  /cv
    defaults: { _controller: JobHubBundle:JobHub:cv}
    
job_hub_offre:
    pattern:  /offre
    defaults: { _controller: JobHubBundle:JobHub:offre}  
    
job_hub_recherche:
    pattern:  /recherche
    defaults: { _controller: JobHubBundle:JobHub:recherche}   
 
job_hub_conseil:
    pattern:  /conseil
    defaults: { _controller: JobHubBundle:JobHub:conseil} 

job_hub_actu:
    pattern:  /actu
    defaults: { _controller: JobHubBundle:JobHub:actu} 
 
job_hub_plan:
    pattern:  /plan
    defaults: { _controller: JobHubBundle:JobHub:plan}          
                      
job_hub_faq:
    pattern:  /faq
    defaults: { _controller: JobHubBundle:JobHub:faq}

job_hub_admin_connect:
    pattern:  /admin_connect
    defaults: { _controller: JobHubBundle:JobHub:admin_connect }

admin_entreprise:
    pattern:  /admin_entreprise
    defaults: { _controller: JobHubBundle:Entreprise:index }
    
admin_entreprise_new:
    pattern:  /admin_entreprise_new
    defaults: { _controller: JobHubBundle:Entreprise:new }

admin_entreprise_create:
    pattern:  /admin_entreprise_create
    defaults: { _controller: JobHubBundle:Entreprise:create }
    
admin_entreprise_edit:
    pattern:  /admin_entreprise_edit/{id}
    defaults: { _controller: JobHubBundle:Entreprise:edit }   

admin_entreprise_show:
    pattern:  /admin_entreprise_show/{id}
    defaults: { _controller: JobHubBundle:Entreprise:show }   
    
job_hub_admin_accueil:
    pattern:  /admin
    defaults: { _controller: JobHubBundle:JobHub:admin }

job_hub_admin_type_liste:
    pattern:  /admin/{type}
    defaults: { _controller: JobHubBundle:JobHub:admin_type_liste}
     
job_hub_admin_type:
    pattern:  /admin/{type}/{id}
    defaults: { _controller: JobHubBundle:JobHub:admin_type }
    

