<?php

namespace JH_Project\JobHubBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExperienceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperienceRepository extends EntityRepository
{
	public function removeExperience($id) 
    {
		$query = $this->getEntityManager()->createQuery(
			'DELETE
			 FROM JobHubBundle:Experience e
			 WHERE e.id = '.$id
			);
		$query->execute();
    }
}
