<?php

namespace JH_Project\JobHubBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModerateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModerateurRepository extends EntityRepository
{
}
