<?php

namespace JH_Project\JobHubBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreRepository extends EntityRepository
{
	public function searchOffre($mot_cle, $lieu){

        $qb = $this->createQueryBuilder('offer');
        $qb	->leftJoin('offer.ville', 'v')
        	->leftJoin('v.region', 'r')   
        	->leftJoin('r.pays', 'p')
        	->where( '(offer.description LIKE :mc 
        		OR offer.intitule LIKE :mc 
        		OR offer.fonctionPoste LIKE :mc)
        		AND (v.nom LIKE :lieu
        		OR r.nom LIKE :lieu
        		OR p.nomFr LIKE :lieu)
        		AND offer.enabled = true'
        		)  
           ->setParameter( 'mc', '%'. $mot_cle .'%' )
           ->setParameter( 'lieu', '%'. $lieu .'%' );
 
        return $qb->getQuery()->getResult();
        
    }

}
