<?php

namespace JH_Project\JobHubBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaysRepository extends EntityRepository
{
}
