security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        JH_Project\JobHubBundle\Entity\Utilisateur: plaintext

    role_hierarchy:
        ROLE_MODERATEUR:  [ROLE_CANDIDAT, ROLE_ENTREPRISE]
        ROLE_REDACTEUR:   [ROLE_CANDIDAT, ROLE_ENTREPRISE]
        ROLE_ADMIN: [ROLE_MODERATEUR, ROLE_REDACTEUR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        users: 
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # fos_user_bundle default fire-wall defined in app/config/config.yml

        # admin login
        admin:
            pattern:  ^/administration
            anonymous: ~
            provider: users
            form_login:
                login_path: /administration/login
                check_path: /administration/login_check
                always_use_default_target_path: true
                default_target_path: /administration/index
            logout:
                path: /administration/logout
                target: /administration/login
            remember_me:
                key: %secret%   
        # admin login end 
        
        # General login
        main:
            pattern:  ^/
            anonymous: true
            provider: users
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: logout
                target: /index
            remember_me:
                key: %secret%

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        # for anonymous users:
        #- { path: ^/candidat/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # entreprises access:
        #- { path: ^/entreprise/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/entreprise/profile/, roles: ROLE_ENTREPRISE }
        - { path: ^/entreprise/offre/, roles: ROLE_ENTREPRISE }
        
        # candidat access:
        #- { path: ^/candidat/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/candidat/profile, roles: ROLE_CANDIDAT }

        # admin access:
        - { path: ^/administration/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administration/, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_MODERATEUR, ROLE_REDACTEUR] }
        - { path: ^/administration/index, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_MODERATEUR, ROLE_REDACTEUR] }
        - { path: ^/administration, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_MODERATEUR, ROLE_REDACTEUR] }

